#---------------------------------------------------------------------
# Manifest File to create AWS EKS Cluster in Custom VPC
#
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
#
# Copyleft (c) by Denis Astahov 2021
#---------------------------------------------------------------------
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : demo-prod
  region: us-west-2
  version: "1.27"

vpc:
  id     : "vpc-0451e8bbc1af8c808"
  subnets:
    public:
      us-west-2a: { id: subnet-0dc4c96e71620e7d6 }  # For Load Balancer
      us-west-2b: { id: subnet-0a1c72ea5c4d623ac }  # For Load Balancer
      us-west-2c: { id: subnet-0582397f9b7e313a7 }  # For Load Balancer
      us-west-2d: { id: subnet-02ef057a0ded38a12 }  # For Load Balancer
#    private:
#       us-west-2a: { id: subnet- }  # For Worker Nodes
#       us-west-2b: { id: subnet- }  # For Worker Nodes


managedNodeGroups:
  - name             : general
    instanceType     : t3.small
    desiredCapacity  : 3
    labels            : { role: general }
    volumeSize        : 70
    privateNetworking: false
